import { Palette } from "std-widgets.slint";

export global LayoutMetrics {
    out property <length> window-width: 320px;
    out property <length> window-height: 240px;

    out property <length> padding: 5px;
}

export component TitleBar inherits Rectangle {
    in property <string> text <=> title-text.text;

    width: 100%;
    height: 30px;
    padding-top: LayoutMetrics.padding;
    padding-bottom: LayoutMetrics.padding;
    background: Palette.alternate-background;

    title-text := Text {
        font-size: 16px;
    }
}

export component StatusBar inherits Rectangle {
    in property <string> text <=> status-text.text;

    height: 24px;
    padding-top: LayoutMetrics.padding;
    padding-bottom: LayoutMetrics.padding;
    background: Palette.alternate-background;

    status-text := Text {
        height: root.height - 2 * LayoutMetrics.padding;
        horizontal-alignment: center;
        vertical-alignment: bottom;
    }
}

export component BarGauge {
    in property <bool> have-data: false;
    in property <bool> stale-data: false;

    in property <float> value: 100;
    in property <float> min-value: -100;
    in property <float> max-value: 100;

    in property <string> unit: "";
    in property <brush> bar-color <=> fill.background;

    property <length> gauge-width: 30px;
    property <length> border-width: 2px;

    // Level is between 0 and 1
	out property <float> level:
	    (Math.clamp(self.value, self.min-value, self.max-value) - self.min-value) / (self.max-value - self.min-value);

    states [
        with-value when root.have-data && root.stale-data: {
            gauge.border-color: Palette.border;
            gauge.opacity: 0.5;
            value-text.visible: true;
            value-text.opacity: 0.5;
            fill.visible: true;
            fill.opacity: 0.5;
        }
        with-value when root.have-data && !root.stale-data: {
            gauge.border-color: Palette.border;
            gauge.opacity: 1.0;
            value-text.visible: true;
            value-text.opacity: 1.0;
            fill.visible: true;
            fill.opacity: 1.0;
        }
        without-value when !root.have-data: {
            gauge.border-color: Palette.alternate-background;
            gauge.opacity: 1.0;
            value-text.visible: false;
            value-text.opacity: 1.0;
            fill.visible: false;
            fill.opacity: 1.0;
        }
    ]

    gauge := Rectangle {
        x: 0;

        width: root.gauge-width;
        height: root.height;

        border-width: root.border-width;
        border-radius: root.gauge-width / 2;

        // Does not work in the software renderer.
        clip: true;

        animate opacity {
            duration: 300ms;
            easing: ease-out;
        }

        fill := Rectangle {
            x: root.border-width;
            y: parent.height - root.border-width - self.height;
            height: (parent.height - 2 * root.border-width) * root.level;
            width: parent.width - 2 * root.border-width;

            background: Colors.red;

            // Workaround for missing parent.clip software renderer support.
            border-bottom-left-radius: root.gauge-width / 2 - root.border-width;
            border-bottom-right-radius: root.gauge-width / 2 - root.border-width;

            animate height {
                duration: 300ms;
                easing: ease-in-out;
            }

            animate opacity {
                duration: 300ms;
                easing: ease-out;
            }
        }
    }

    value-text := Text {
        text: Math.round(root.value * 10) / 10 + root.unit;
        font-size: 32px;
        x: root.gauge-width + LayoutMetrics.padding;

        animate opacity {
            duration: 300ms;
            easing: ease-out;
        }
    }
}
